---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fancysecrets-secretsauce-anthonymilazzo-com-v1-randomsecret
  failurePolicy: Fail
  name: vrandomsecret.kb.io
  rules:
  - apiGroups:
    - fancysecrets.secretsauce.anthonymilazzo.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - randomsecrets
  sideEffects: None
