# permissions for end users to edit secretpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secretpolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secretsauce
    app.kubernetes.io/part-of: secretsauce
    app.kubernetes.io/managed-by: kustomize
  name: secretpolicy-editor-role
rules:
- apiGroups:
  - fancysecrets.secretsauce.anthonymilazzo.com
  resources:
  - secretpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fancysecrets.secretsauce.anthonymilazzo.com
  resources:
  - secretpolicies/status
  verbs:
  - get
