apiVersion: fancysecrets.secretsauce.anthonymilazzo.com/v1
kind: SecretPolicy
metadata:
  labels:
    app.kubernetes.io/name: secretpolicy
    app.kubernetes.io/instance: secretpolicy-sample
    app.kubernetes.io/part-of: secretsauce
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: secretsauce
  name: secretpolicy-sample
spec:
  minLength: 12
